INDIA_CROPS = sorted([
    "Wheat",
    "Rice",
    "Paddy(Dhan)(Common)",
    "Maize",
    "Jowar(Sorghum)",
    "Bajra(Pearl Millet)",
    "Barley",
    "Ragi(Finger Millet)",
    "Small Millets",
    "Arhar(Tur/Red Gram)",
    "Gram(Chana)",
    "Moong(Green Gram)",
    "Urad(Black Gram)",
    "Masur(Lentil)",
    "Peas",
    "Rajma",
    "Cowpea(Lobia)",
    "Horse Gram",
    "Groundnut",
    "Mustard",
    "Soyabean",
    "Sunflower",
    "Sesame(Til)",
    "Castor Seed",
    "Linseed",
    "Niger Seed",
    "Safflower",
    "Cotton",
    "Sugarcane",
    "Jute",
    "Tobacco",
    "Potato",
    "Onion",
    "Tomato",
    "Brinjal",
    "Cabbage",
    "Cauliflower",
    "Carrot",
    "Radish",
    "Green Chilli",
    "Capsicum",
    "Cucumber",
    "Bottle Gourd",
    "Bitter Gourd",
    "Ridge Gourd",
    "Pumpkin",
    "Okra(Bhindi)",
    "Peas(Vegetable)",
    "Spinach",
    "Beetroot",
    "Garlic",
    "Ginger",
    "Sweet Potato",
    "Colocasia(Arbi)",
    "Tapioca",
    "Banana",
    "Mango",
    "Apple",
    "Grapes",
    "Orange",
    "Papaya",
    "Guava",
    "Pomegranate",
    "Sapota(Chikoo)",
    "Watermelon",
    "Muskmelon",
    "Pineapple",
    "Litchi",
    "Lemon",
    "Sweet Lime(Mosambi)",
    "Custard Apple",
    "Jackfruit",
    "Coconut",
    "Turmeric",
    "Coriander",
    "Cumin(Jeera)",
    "Chilli(Dry)",
    "Black Pepper",
    "Cardamom",
    "Fenugreek(Methi)",
    "Fennel",
    "Ajwain",
    "Clove",
    "Nutmeg",
    "Tea",
    "Coffee",
    "Rubber",
    "Arecanut",
    "Cashewnut",
    "Groundnut Pods",
])